
package cn.lianrf.webservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayHelloImpl", targetNamespace = "http://server.webservice.lianrf.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayHelloImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say1", targetNamespace = "http://server.webservice.lianrf.cn/", className = "cn.lianrf.webservice.client.Say1")
    @ResponseWrapper(localName = "say1Response", targetNamespace = "http://server.webservice.lianrf.cn/", className = "cn.lianrf.webservice.client.Say1Response")
    @Action(input = "http://server.webservice.lianrf.cn/SayHelloImpl/say1Request", output = "http://server.webservice.lianrf.cn/SayHelloImpl/say1Response")
    public String say1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say2", targetNamespace = "http://server.webservice.lianrf.cn/", className = "cn.lianrf.webservice.client.Say2")
    @ResponseWrapper(localName = "say2Response", targetNamespace = "http://server.webservice.lianrf.cn/", className = "cn.lianrf.webservice.client.Say2Response")
    @Action(input = "http://server.webservice.lianrf.cn/SayHelloImpl/say2Request", output = "http://server.webservice.lianrf.cn/SayHelloImpl/say2Response")
    public List<Object> say2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
