server:
  port: 8080

spring:
  datasource:
    masterDataSource:
      name: masterDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/learn
      username: root

    slaveDataSource:
      name: slaveDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/learn2
      username: root

  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8
  cache:
    ehcache:
      config: cache/ehcache.xml
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: cn.lian.entity
  type-handlers-package: cn.lian.typehandler
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    lazy-load-trigger-methods:
    default-executor-type: reuse

#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志
logging:
  level:
    cn:
      lian:
        mapper: debug
  file: C:\Users\lianrongfa\Desktop\log.log
my:
  values: hahaha