server:
  port: 8080

spring:
  datasource:
    masterDataSource:
      name: masterDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/learn
      username: root
      password: root
    slaveDataSource:
      name: slaveDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/learn2
      username: root
      password: root
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: cn.lian.entity
  type-handlers-package: cn.lian.typehandler
#pagehelper\u5206\u9875\u63D2\u4EF6
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志
logging:
  level:
    cn:
      lian:
        mapper: debug
  file: C:\Users\lianrongfa\Desktop\log.log
my:
  values: hahaha